version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: task-management-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=task-management
    networks:
      - task-management-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-management-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/task-management
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000
      - SOCKET_CORS_ORIGIN=http://localhost:3000
    networks:
      - task-management-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-management-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge

volumes:
  mongodb_data:
